[package]
name = "kich"
version = "0.0.0"
description = "ğŸ” Fast and secure password manager."
authors = ["NehuÃ©n/Neth"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = [] }
tauri-plugin-shell = "2.0.0-beta"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
aes-gcm = "0.10.3"
hex = "0.4.3"
dirs = "5.0.1"
polodb_core = "4.4.1"
tauri-plugin-store = "2.0.0-beta.6"
